### ISSUE TITLE
Adding in more Enigma Models

### ISSUE THREAD

**Issue by DonaldTsang** [cedricbonhomme/pyEnigma#1]
Reference: https://github.com/vanitasvitae/EnigmAndroid  
List of Enigma Machines: https://github.com/vanitasvitae/EnigmAndroid/tree/master/app/src/main/java/de/vanitasvitae/enigmandroid/enigma  
- [ ] Model D
- [ ] Model G260
- [ ] Model G31
- [ ] Model G312
- [ ] Model K
- [ ] Model KD
- [ ] Model K Swiss Airforce
- [ ] Model K Swiss Standard
- [ ] Model R
- [ ] Model T

**Comment by cedricbonhomme** [comment]
Thanks for the link, I'll add more rotor from EnigmAndroid.
